homeSuccess:
  stylesheets: [/opBlogPlugin/css/blog]

profileSuccess:
  stylesheets: [/opBlogPlugin/css/blog]
  customize:
    blogProfile:
      template: [blog, blogProfile]
      parts: [profile]
      is_component: true
      target: [lastRaw]
