blogHomeFriend:
  caption:
    ja_JP: "フレンドの最新ブログ"
  description:
    ja_JP: "フレンドの最新のブログの一覧を表示します。"
  component: [blog, blogHomeFriend]
blogHomeUser:
  caption:
    ja_JP: "自分の最新ブログ"
  description:
    ja_JP: "自分の最新のブログの一覧を表示します。"
  component: [blog, blogHomeUser]
