blogUrl:
  _attributes:
    caption: "BlogのURL設定"
  blog_url:
    Name:       "blog_url"
    Caption:    "BlogのURL"
    FormType:   "input"
    ValueType:  "blog_url"
    IsRegist:   false
    IsConfig:   true
    IsUnique:   false
    IsRequired: false
    IsConfirm:  false
